name: Nightly Pipeline

on:
  schedule:
    # Runs Monday to Friday at 23:00 UTC
    - cron: '00 23 * * 1-5'
  workflow_dispatch:
    inputs:
      suite:
        description: 'Choose automation suite: RegressionSuite, SmokeSuite, SanitySuite'
        required: true
        default: RegressionSuite
      browser:
        description: 'Choose browser suite: chrome, edge, firefox'
        required: true
        default: chrome

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Run Automation Suite
        run: |
          # Use provided inputs if present, otherwise fall back to defaults
          SUITE="${{ github.event.inputs.suite }}"
          BROWSER="${{ github.event.inputs.browser }}"

          # Set fallback defaults for nightly scheduled runs
          if [ -z "$SUITE" ]; then SUITE="RegressionSuite"; fi
          if [ -z "$BROWSER" ]; then BROWSER="chrome"; fi

          mvn clean install -DciCd=true -Dbrowser=$BROWSER -DsuiteXmlFile=suites/$SUITE -PCustomSuite
